apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: flux-system
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:66oxHecLR74=,iv:ZRGlX0w48QltEWunWeOB1bsFCo2SaNdwC89mghVK2bY=,tag:ciiHvtO11MfZjmxIopQXOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuelZQMzRmS25SRnNiQ3dj
            dURId0YvR3diRzJqNjV6aXp3QWZ1VWVDMEFFCjNZZ2UrTWJicDExaGFmU0l6aVlo
            cGtMUXJ0SnFDTVJoU045QXJPbFg2YkkKLS0tIHhnUW1yV1doSy8rd3VYell3UlJx
            SWhlQzBnTk1YTmM1OWJDTUpyalJnNUEKOd1tBv2yZONxxHlixI//X5Breg9j01Du
            uULhM3ba9Xtm2PpjS6FAlhJ/UP/UYDuJ/kC2eIYDNRNf6/MX9YockQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n9cv99ewmn862y0yxwhg34mcg6dr4sjyjjkpdw38ngl7ax8fwezq637nwh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T23:26:56Z"
    mac: ENC[AES256_GCM,data:H/7r21lp4hX8zo+bwt5k0uG6Lc4VvQuksp5NRqHEdpRUwoZgK4BcEinlGssR4i/jFRDd3sBu7CMb+GEd7K6PQcWIoW3Wq3kxLeki3drEjaPGnUpcMpON5vs9TYCi5XIKz8FqRk5WFQ2yjQp6hyIAepRvSINik/GSD2ffv2HcMhQ=,iv:TgYzqzjxor3R8qaRfaSxTnvSB5Sf8h87EYLj0NqsjtA=,tag:2MCNgcHsUax0VG2W4Z+iCA==,type:str]
    version: 3.13.1
