---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 7.3.10
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
