apiVersion: v1
kind: Secret
metadata:
    name: boinc-projects-secret
    namespace: boinc
type: Opaque
stringData:
    gui-rpc-password: ENC[AES256_GCM,data:FCUf9UBH14s=,iv:ZzrVlO12ekWCUTXZOBUdMlq5tk9CmhMgbJPdGmN/Ex4=,tag:n721pO7lCGHpwrjh5rTAuA==,type:str]
    account_boinc.bakerlab.org_rosetta.xml: ENC[AES256_GCM,data:nDBFVz67x+SdST2nOpreQCA2TN87if5bK6uG+GxxdAA23xOgYUA4Gwj/Z8WTfu3yBOLMazouz7JnkkuhVJNd/YRasKb/A/H99al4jBlvf6n+BkOhPR8Vhx9gr7O2dqLGEpiVwWQ8s1K3AW4/WuIYK9F2slSq/CAO/nNe64FhqmYA/1OyB9HYRazs9SAp3vgZWzscy+QpBSOsA4fgJpYchcnGlHRu1FI0yZuzq67qG50jQ0S+3ysshHBwNnf8uu2lqug8LfdOMkHROUmgKa4MIor01YlUBe3KNjZak/Pf21mnTXwnWd/+W1mWamO0oRTAuIUrmSrrQnUZlc0ZbwDiSY36vg==,iv:CZQ9a2grX86sUm2uLN51F0F5ooi+H/AZpZC2qHpw63g=,tag:1ADEVwP+esnOSqqPZ7tmaA==,type:str]
    account_einstein.phys.uwm.edu.xml: ENC[AES256_GCM,data:P5sY8UHSQPzf2NR5RW6WJhmEIepdtpuis4Y7kUKRxseSimxvpfJf0XxOc8qAtj5H8n794FufQ7aSBZqHSwXWT8UwtIwOeYKIwL7EL7WEkClQJegyh+Vqs1Ob68EmqUWSRN4eM5kRZXf+nEL+t0YqofrtZoaRWIA+9xDugPvYu4q+qGctIk0Y/iSi5iqPoT1DGL56RvAm3JV4gmi06Szo71+0bqNc23aiDIxnqLKm3a/EvpEU0oxCVAtLSMkV93PfeWv4YwjxOHLAlcROeigZ/aVDZFKC3nOZE3dxPIPkf0p+DjKyZzu7WRZmjFQkN18GbK/CQgfYZCSxhgtsqF1h,iv:6BFitw0RNSh5FhMV3NBpcGVOozTdZJObaHB2aHAhTeU=,tag:g2PAiALvpEst7mOuLitWJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY2VLVjZPSGJoeW5sQi9z
            S3Q2WVpJVmxnMDlGUVE0UXIzSk9wQSs5clJvCjFYUGVrVXUzdnl6TVpNTjUxeUc4
            UkQwd1dsSllGYTI2UEFvbVdMWTVLTUUKLS0tIDBFbXpiMFB2UldZdHNKOEhpd3VO
            ZmYzWUVUdzFRNTJCVkluNWxvOC9EUk0KRvwu0xQLsOalKfd03TzO10lwm3T6GfE9
            PjDhEL7f5rihF1gaNfG2Xu6J8B3AqBJdCRJk+IDbzlDtUVzBuvavpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n9cv99ewmn862y0yxwhg34mcg6dr4sjyjjkpdw38ngl7ax8fwezq637nwh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T15:14:56Z"
    mac: ENC[AES256_GCM,data:q/HXefszCaGighuzO2om6ZODvjBv/pI/7IJYKaPuK2oo/Qjofx+BvgGgeW+TcAQ0k9y5Jh7DNAoDcnY4SWwmHjaakTpf3Xjy37a7Zph5sgm9mSOjLbjg9FOZBg/PpZ6uXUWbT7kPbOVCBP25iHUkYZnnxkvn/+pQGUea5MzwmSA=,iv:dbVIjv8yVzWCa7Xn/D6eHWKE5cvqKhUj7erMGhlEDCA=,tag:GMoy4BlMO14rUA0aBgKX3w==,type:str]
    version: 3.13.1
