apiVersion: v1
kind: Secret
metadata:
    name: boinc-secret
    namespace: boinc
type: Opaque
stringData:
    gui-rpc-password: ENC[AES256_GCM,data:fVeHIYE5d9Y=,iv:yd9BWgpZuhQyux6+B7y/gkIwf3oYK5eWga50VA3j8tw=,tag:jUx3tgx3rhIqO9ZI97XwXQ==,type:str]
    project-key: ENC[AES256_GCM,data:iZfZswZawZk1Cw9oGswvenRpW0sbPFTV6esLAKRKqPfQxhoqQRn+,iv:FEpoiBe5PnRH25MzrfZ2iPZAzrz5A2cZloL2OnF7Tik=,tag:DYNpXwuM7pwAxNd7vwvEqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUDZQcVJXWXAwUlhyTVNL
            MGk3UWU5U2ozVWtxUzJtVm1QQVg3MEF4OGdJCk9zbm1OcVVBMVBzK2xxbXI2MVI5
            bkVBU1lSZ3lGS1QwTzJqUnNPVlgvOTAKLS0tIFpZRVhkMTJHeHpQSnZDaS9jaGM4
            L3hpYUlBZ0lSWkNaamZnQzFqSzQ3RTQKKpd0UU012n9l0Xp46UOiCM8WoVxr+gTh
            6YakKaqI+1r26AdveW9emBm0lKn1agcbU4ests/n/StWvg7Orj7dgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n9cv99ewmn862y0yxwhg34mcg6dr4sjyjjkpdw38ngl7ax8fwezq637nwh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T16:51:26Z"
    mac: ENC[AES256_GCM,data:IW1bt98QuHzuUdkiqCTaBeZCw6tdkqqBBBeWk2NyEfYswCN+gLvLcLYGWr7vpGeJsDYJJz7gkVRrd8nNMAnhOKLWlcshzuQJPRwjJQx8ZjTljjcT1WoBoaJWGhD9aYe+S9cFw5FxgC7e7btre+HWtqfpX920QRgyV4/bh1HrSNk=,iv:eFWq0YL3eVl86Q7PdtiH2SiaYgfOA88po9RQAtRBSJM=,tag:WeeBVuv44zZ7Y5pBhArMmA==,type:str]
    version: 3.13.1
