---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/starboard-operator/values.yaml
  - ../../../base/starboard-operator/helm-repository.yaml
  - ../../../base/starboard-operator/helm-release.yaml
