apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repositories.yaml
  - cilium.yaml
  - cert-manager.yaml
  - openebs.yaml
  - istio.yaml
  - envoy-gateway.yaml
  - tetragon.yaml
  - kyverno.yaml
  - kubescape.yaml
  - falco.yaml
