---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-operator
  namespace: starboard-system
spec:
  suspend: true # <-- set to true to disable without deleting
  interval: 10m
  chart:
    spec:
      chart: starboard-operator
      version: 0.8.1
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
  values:
    targetNamespaces: ""
    trivy:
      ignoreUnfixed: true
