---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: istiod
      version: 1.21.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    global:
      istioNamespace: istio-system
    gateways:
      istio-ingressgateway:
        enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
