---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: istiod
      version: "1.26.0"
      sourceRef:
        kind: HelmRepository
        name: istio
  dependsOn:
    - name: istio-base
  values:
    telemetry:
      enabled: true
    pilot:
      traceSampling: 10.0
