---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  targetNamespace: istio-system
  interval: 1h0m0s
  chart:
    spec:
      chart: base
      # Pin the version for stability, but allow patch updates.
      version: "~1.22.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
