---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
      namespace: flux-system
  interval: 1h0m0s
  chart:
    spec:
      # Pin the version for stability, must match the 'base' chart version.
      version: "~1.22.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    pilot:
      autoscaleEnabled: false
      traceSampling: 10.0
    telemetry:
      enabled: true
