---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  targetNamespace: istio-system
  interval: 1h
  chart:
    spec:
      chart: gateway
      version: "~1.22.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  dependsOn:
    - name: istiod
      namespace: flux-system
  values:
    # For KinD, you may need to map the service ports to the host.
    # See the KinD documentation on "Extra Port Mappings":
    # https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings
    service:
      type: LoadBalancer
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
