---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: base
      version: "1.26.0"
      sourceRef:
        kind: HelmRepository
        name: istio
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
