---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
<<<<<<< HEAD
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
      namespace: flux-system
  interval: 1h
||||||| 33162ea (chore: added dependsOn field under spec)
  dependsOn:
    - name: istio-base
      namespace: istio-system
  interval: 1h0m0s
=======
  interval: 1h0m0s
>>>>>>> parent of 33162ea (chore: added dependsOn field under spec)
  chart:
    spec:
      chart: istiod
      # Pin the version for stability, must match the 'base' chart version.
      version: "~1.22.1"
      sourceRef:
        kind: HelmRepository
        name: istio
<<<<<<< HEAD
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
||||||| 33162ea (chore: added dependsOn field under spec)
        namespace: istio-system
=======
  dependsOn:
    - name: istio-base
>>>>>>> parent of 33162ea (chore: added dependsOn field under spec)
  values:
    pilot:
      autoscaleEnabled: false
      traceSampling: 10.0
    telemetry:
      enabled: true
