---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: istiod
      # Pin the version for stability, must match the 'base' chart version.
      version: "~1.22.1"
      sourceRef:
        kind: HelmRepository
        name: istio
  dependsOn:
    - name: istio-base
  values:
    pilot:
      autoscaleEnabled: false
      traceSampling: 10.0
    telemetry:
      enabled: true
