---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
      namespace: istio-system
  interval: 1h0m0s
  chart:
    spec:
      chart: istiod
      version: "1.26.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  values:
    telemetry:
      enabled: true
    pilot:
      traceSampling: 10.0
