---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 1h
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: "1.15"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  values:
    telemetry:
      enabled: true
    pilot:
      traceSampling: 100
