---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/grafana
namespace: monitoring
generatorOptions:
  disableNameSuffixHash: true
labels:
  app.kubernetes.io/managed-by: flux
