---
container:
  image: "docker.io/mpolden/echoip"
  pullPolicy: IfNotPresent
  tag: "latest"
  commandargs:
    - "-H"
    - "X-Forwarded-For"

namespace: reflector

service:
  type: ClusterIP
  port: 8080

nodePort:
  enabled: false
  port: ""

resources:
  cpu:
    request: "10m"
    limit: "100m"
  memory:
    request: "20Mi"
    limit: "50Mi"

securityContext:
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

geoDB:
  enabled: false
  secret:
    name: " "
    key: " "
