---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 10m
  timeout: 10m # 👈 Increase from default 5m
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      version: "3.10.0"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
  values:
    apiserver:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi

    provisioner:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi

    localprovisioner:
      enabled: true # ✅ Keep this enabled for hostPath-based volumes
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi

    snapshotOperator:
      controller:
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
      provisioner:
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi

    ndm:
      enabled: false # ✅ Disable NDM (not needed in KinD)
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi

    ndmOperator:
      enabled: false
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi

    cstor:
      enabled: false

    webhook:
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 500m
          memory: 1Gi

    jiva:
      enabled: false

    zfsLocalPv:
      enabled: false
