---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/overlays/kind/monitoring-namespaces ## Needs to be first
  - ../../apps/overlays/kind/sources ## Needs to be second
  - ../../apps/overlays/kind/cert-manager
  - ../../apps/overlays/kind/istio
  - ../../apps/overlays/kind/openebs
  - ../../apps/overlays/kind/prometheus
  - ../../apps/overlays/kind/grafana
  - ../../apps/overlays/kind/echoip
  - ../../apps/overlays/kind/starboard-operator
