---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: echoip
  namespace: reflector
spec:
  releaseName: echoip
  interval: 1m
  chart:
    spec:
      chart: ./charts/echoip
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    replicaCount: 1
