---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: echoip
  namespace: echoip
spec:
  releaseName: echoip
  interval: 5m
  chart:
    spec:
      chart: echoIP
      sourceRef:
        kind: HelmRepository
        name: echoip
        namespace: flux-system
