---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: echoip
  namespace: echoip
spec:
  interval: 5m
  chart:
    spec:
      chartPath: "./apps/base/echoip"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
