---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: echoip
  namespace: echoip
spec:
  releaseName: echoip
  interval: 1m
  chart:
    spec:
      chart: echoIP # folder name inside the repo
      sourceRef:
        kind: GitRepository
        name: echoip
        namespace: flux-system
  values:
    replicaCount: 1
