---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echoip
  namespace: echoip
spec:
  interval: 5m
  chart:
    spec:
      chart: echoIP # subfolder inside repo
      sourceRef:
        kind: GitRepository
        name: echoip
        namespace: flux-system
  values:
    replicaCount: 1
