---
apiVersion: networking.istio.io/v1
# https://istio.io/latest/docs/reference/config/networking/gateway/
kind: Gateway
metadata:
  name: echoip-gateway
  namespace: echoip
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1
# https://istio.io/latest/docs/reference/config/networking/virtual-service/#VirtualService-hosts
kind: VirtualService
metadata:
  name: echoip
  namespace: echoip
spec:
  hosts:
    - "*"
  gateways:
    - echoip-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: echoip-service
            port:
              number: 8080
